/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avatar.def
	public class EntityBaseEntityCall_AvatarBase : EntityCall
	{

		public EntityBaseEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void EnterRoom(Byte arg1)
		{
			Bundle pBundle = newCall("EnterRoom", 0);
			if(pBundle == null)
				return;

			bundle.writeUint8(arg1);
			sendCall(null);
		}

		public void LeaveRoom()
		{
			Bundle pBundle = newCall("LeaveRoom", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AvatarBase : EntityCall
	{

		public EntityCellEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void PlaceCard(CMD arg1)
		{
			Bundle pBundle = newCall("PlaceCard", 0);
			if(pBundle == null)
				return;

			((DATATYPE_CMD)EntityDef.id2datatypes[25]).addToStreamEx(bundle, arg1);
			sendCall(null);
		}

	}
	}
